[package]
name = "dropterm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29"
egui = "0.27"
egui-winit = "0.27"
egui-wgpu = "0.27"
wgpu = "0.19"
crossbeam-channel = "0.5"
win-hotkeys = "0.3"
pollster = "0.3"