[package]
name = "dropterm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29.15", features = ["rwh_05"] }
softbuffer = "0.4.6"
global-hotkey = "0.6.4"
conpty = "0.5.1"
rusttype = "0.9.3"
anyhow = "1.0.75"
keyboard-types = "0.7.0"