[package]
name = "dropterm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29.15", features = ["rwh_06"] }
wgpu = "0.19.3"
egui = "0.27.2"
egui-winit = "0.27.2"
egui-wgpu = "0.27.0"
pollster = "0.3"
raw-window-handle = "0.6"