[package]
name = "dropterm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"
egui = "0.25"
win-hotkeys = "0.5.0"
crossbeam-channel = "0.5.14"
windows-sys = { version = "0.59.0", features = ["Win32", "Win32_Graphics", "Win32_Graphics_Gdi"] }
